apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-home-front
  name: web-home-front
  namespace: web-home
spec:
  ports:
    - name: "8110"
      port: 8110
      targetPort: 8110
  selector:
    app: web-home-front
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-home-front
  name: web-home-front
  namespace: web-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-home-front
  strategy:
    type: RollingUpdate
  template:
    metadata:

      labels:
        app: web-home-front
    spec:
      priorityClassName: high-priority
      imagePullSecrets:
      - name: harbor-config
      containers:
      - image:  harbor.pivotstudio.cn/hr-system/hr-front:{{.build_tag}}
        name: web-home-front
        ports:
          - containerPort: 8110
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests: 
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-home-front
  namespace: web-home
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-home-front
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70


